services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_USERNAME: username
      MONGO_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
